server:
  port: 8088

spring:
  jackson:
    time-zone: GMT+8
    dateFormat: YYYY-MM-dd HH:mm:ss

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.201.239.223:3306/watch_box?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: Tf511925.
    hikari:
      connection-timeout: 30000       # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException， 默认:30秒
      minimum-idle: 5                 # 最小连接数
      maximum-pool-size: 20           # 最大连接数
      auto-commit: true               # 自动提交
      idle-timeout: 60000             # 连接超时的最大时长（毫秒），超时则被释放（retired），默认:10分钟
      pool-name: DateSourceHikariCP   # 连接池名字
      max-lifetime: 180000            # 连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认:30分钟 1800000ms
      connection-test-query: SELECT 1


mybatis:
  mapper-locations: classpath:mapper/*.xml
# 通用 mapper
# 主键自增回写方法,默认值MYSQL
mapper:
  identity: MYSQL
  not-empty: false


pagehelper:
  # 使用的sql方言
  helperDialect: mysql
  # 是否启用合理化，默认false，启用合理化时，如果 pageNum<1会查询第一页，如果pageNum>pages会查询最后一页
  reasonable: true
  # 是否支持通过Mapper接口参数来传递分页参数，默认false
  #pagehelper.supportMethodsArguments=true
  params: count=countSql
